export const MAKER_SECTIONS = {
  PRODUCTS: 'PRODUCTS',
  REVIEWS: 'REVIEWS',
  QUESTIONS: 'QUESTIONS',
  DETAILS: 'DETAILS',
};

export const MY_BUSINESS_SECTIONS = {
  PRODUCTS: 'PRODUCTS_ADMIN',
  QUOTATIONS: 'QUOTATIONS_ADMIN',
  SALES: 'SALES_ADMIN',
  INFO: 'INFO_ADMIN',
  QUESTIONS: 'QUESTIONS_ADMIN',
};

export const MY_PURCHASES_SECTIONS = {
  PURCHASES: 'PURCHASES',
  QUOTATIONS: 'QUOTATIONS',
};

export const GRAPHQL_SORT_ENUMS = {
  ASC: 'asc',
  DESC: 'desc',
};

export const PAGINATION = {
  defaultSize: 10,
};
